inherit_from:
  - .rubocop_todo.yml
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

#以下にはrubocopで検証したくないフォルダを指定する
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'

Layout/LeadingCommentSpace:
  Exclude:
    - 'node_modules/node-sass/src/libsass/extconf.rb'

Metrics/LineLength:
  Max: 103
